apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wego-chart
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/weave-gitops
      sourceRef:
        kind: GitRepository
        name: test-chart
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
